server:
  port: 8080

spring:
  application:
    name: promptcraft
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
